#-------------------------------------------------------------------------
# TITLE: 
#    pkgModules.tcl
#
# PROJECT:
#    igloo: Your project description
#
# DESCRIPTION:
#    igloo(n): Package Loader
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Provide Package

# -quill-provide-begin DO NOT EDIT BY HAND
package provide igloo 0.0a0
# -quill-provide-end

#-------------------------------------------------------------------------
# Require Packages

# -quill-require-begin INSERT PACKAGE REQUIRES HERE
# -quill-require-end

#-------------------------------------------------------------------------
# Get the library directory

namespace eval ::igloo:: {
    variable library [file dirname [info script]]
}

source [file join $::igloo::library igloo.tcl]
